env: QA
base_url: "https://rahulshettyacademy.com/angularpractice/"
username: "devuser"
password: "devpass"
letcode_url: "https://letcode.in/"
sauseLab_url: "https://www.saucedemo.com/"


wyy_login_url: https://study.163.com/ 
email: 18183143742
password: www123lzj@

